config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'static_pages/visual_components'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'home#root'

  get 'trazabilidad', to: 'traceability#endpoints_info'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :schemas, only: [:index, :new, :create], param: :name do
    collection { get 'search' }
    resources :schema_versions,
      only: [:index, :new, :create, :show], param: :version_number,
      path: 'versions'
  end

  resources :services, only: [:index], controller: 'home' do
    collection do
      get 'search'
      get 'pending_approval'
    end
  end

  namespace :agreements do
    get 'global'
    get 'new_injection'
    post 'inject'
  end

  namespace :monitoring do
    resources :organizations, only: [:index], param: :name do
      resources :services, only: [:index, :show], param: :name do
        member do
          post 'enable'
          post 'disable'
        end
      end
    end
  end

  resources :monitor_params
  resources :data_categories
  resources :data_directories, only: :index

  resources :organizations, only: [:index, :show], param: :name do
    resources :services, only: [:index, :new, :create, :show], param: :name do
      post 'oauth/token', to: 'services#client_token'
      resources :service_versions,
        only: [:index, :new, :create, :show], param: :version_number,
        path: 'versions' do
          member do
            patch 'reject'
            patch 'state'
            get 'source_code'
            get 'operations/:verb*path', to: 'service_versions#show', as: 'operation', constraints: {path: /\/.*/}
            get 'operations/:verb', to: 'service_versions#show', as: 'operation_on_root_path'
            post 'operations/:verb*path', to: 'service_versions#try', as: 'try_operation', constraints: {path: /\/.*/}
            post 'operations/:verb', to: 'service_versions#try', as: 'try_operation_on_root_path'
          end
      end
    end

    resources :agreements, only: [:index, :new, :create, :show] do
      patch 'state/:next_step' => 'agreements#flow_actions_router', as: 'change_state'
      resources :agreement_revisions, only: [:show, :new, :create], param: :revision_number,
        path: 'revisions'
    end
  end

  resources :users, only: [:index] do
    resources :notifications, only:[:index, :show]
  end

  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/data_category.rb
class DataCategory < ApplicationRecord
  has_many :service_data_categories, dependent: :destroy
  has_many :schema_data_categories, dependent: :destroy
  has_many :services, through: :service_data_categories
  has_many :schemas, through: :schema_data_categories
end

app/controllers/data_categories_controller.rb
class DataCategoriesController < ApplicationController
  before_action :check_service_admin

  def index
  end

  def new
    @data_category = DataCategory.new
  end

  def create  
    @data_category = DataCategory.new(data_category_params)
    if @data_category.save
      redirect_to data_categories_path, notice: t(:record_created)
    else
      flash.now[:error] = t(:couldnt_save_record)
      redirect_to data_categories_path
    end
  end

  def edit
    @data_category = DataCategory.find(params[:id])
  end

  def update
    @data_category = DataCategory.find(params[:id])
    if @data_category.update!(data_category_params)
      flash[:success] = I18n.t(:data_category_update_success)
      redirect_to data_categories_path
    else
      flash[:error] = I18n.t(:data_category_update_error)
      redirect_to data_categories_path
    end
  end

  def destroy
    if DataCategory.find(params[:id]).destroy
      flash[:success] = I18n.t(:data_category_deletion_success)
      redirect_to data_categories_path
    else
      flash[:error] = I18n.t(:data_category_deletion_error)
      redirect_to data_categories_path
    end
  end

  private
  def data_category_params
    params.require(:data_category).permit(:name)
  end

  def check_service_admin
    unless user_signed_in? && current_user.is_service_admin?
      redirect_to services_path, notice: t(:cant_manage_data_categories)
    end
  end

end

app/helpers/data_categories_helper.rb
module DataCategoriesHelper
end

app/views/data_categories/edit.html.haml
= form_for @data_category do |f|
  .col-md-3
    %h2
      = t(:edit_data_category)
    .field
      = f.label :name, "Nombre"
    .field
      = f.text_field :name, class: "form-control input-lg user-success"
    = f.submit t(:send_data), class: "btn btn-action-blue btn-lg gradient"
  
  

app/views/data_categories/index.html.haml
- if !user_signed_in?
  .alert.info
    .container
      %p
        #{t(:identify_with_clave_unica)}
        = link_to t(:identify_with_clave_unica), user_clave_unica_omniauth_authorize_path
- else
  .content-pages.container-fluid
    .container
      .row
        .col-md-12.head-title-table
          .search-table
            %input.search-filter{:type => 'text', :placeholder => t(:name_search), data: {target: '#data_categories_index_table'}}
            %button.search
              %i.material-icons
                search
          %table.table#data_categories_index_table
            %thead
              %tr
                %th
                  = t(:category_name)
                %th
                  = t(:actions)
            %tbody
              - DataCategory.all.each do |cat|
                %tr
                  %td
                    = cat.name
                  %td
                    = link_to t(:edit), edit_data_category_path(cat.id), method: :get                    
                    %a{"data-target" => ".data-category-#{cat.id}", "data-toggle" => "modal", :type => "button"}
                      = t(:destroy)
                    %div{class: "data-category-#{cat.id} modal fade", :role => "dialog", :tabindex => "-1"}
                      .modal-dialog
                        .modal-content
                          .modal-header
                            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                              %span{"aria-hidden" => "true"} ×
                            %h1{style: 'text-align: center'}
                              = t(:delete_data_category)
                          = form_for cat, :url => data_category_path(cat.id), method: :delete do |f|
                            .modal-body
                              .col-md-12
                                %h2{style: 'text-align: center'}
                                  = t(:really_delete_category?)
                              %span.row
                                .col-md-8.col-md-offset-4
                                  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"}
                                    = t(:cancel)
                                  %button.btn.btn-danger{:type => "submit"}
                                    = t(:destroy)
      = button_to t(:create_data_category), new_data_category_path, method: :get, class: "btn btn-action-blue btn-lg gradient"

app/views/data_categories/new.html.haml
.new-agreement.main-container
  .container-fluid.main-title
    .container
      .row
        .col-md-12
          %h1
            = t(:create_data_category)
  .container-fluid
    .container
      .row.new-service-container
        = form_for @data_category do |f|
          .row
            .col-md-4
              %h4
                = t(:category_name)
          .row
            .col-md-4
              = f.text_field :name, class: "form-control input-lg user-success"
          .col-md-4.col-md-offset-8
            = f.submit t(:send_data), class: "btn btn-primary btn-lg col-md-offset-4"