config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'static_pages/visual_components'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'home#root'

  get 'trazabilidad', to: 'traceability#endpoints_info'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :schemas, only: [:index, :new, :create], param: :name do
    collection { get 'search' }
    resources :schema_versions,
      only: [:index, :new, :create, :show], param: :version_number,
      path: 'versions'
  end

  resources :services, only: [:index], controller: 'home' do
    collection do
      get 'search'
      get 'pending_approval'
    end
  end

  namespace :agreements do
    get 'global'
    get 'new_injection'
    post 'inject'
  end

  namespace :monitoring do
    resources :organizations, only: [:index], param: :name do
      resources :services, only: [:index, :show], param: :name do
        member do
          post 'enable'
          post 'disable'
        end
      end
    end
  end

  resources :monitor_params
  resources :data_categories
  resources :data_directories, only: :index

  resources :organizations, only: [:index, :show], param: :name do
    resources :services, only: [:index, :new, :create, :show], param: :name do
      post 'oauth/token', to: 'services#client_token'
      resources :service_versions,
        only: [:index, :new, :create, :show], param: :version_number,
        path: 'versions' do
          member do
            patch 'reject'
            patch 'state'
            get 'source_code'
            get 'operations/:verb*path', to: 'service_versions#show', as: 'operation', constraints: {path: /\/.*/}
            get 'operations/:verb', to: 'service_versions#show', as: 'operation_on_root_path'
            post 'operations/:verb*path', to: 'service_versions#try', as: 'try_operation', constraints: {path: /\/.*/}
            post 'operations/:verb', to: 'service_versions#try', as: 'try_operation_on_root_path'
          end
      end
    end

    resources :agreements, only: [:index, :new, :create, :show] do
      patch 'state/:next_step' => 'agreements#flow_actions_router', as: 'change_state'
      resources :agreement_revisions, only: [:show, :new, :create], param: :revision_number,
        path: 'revisions'
    end
  end

  resources :users, only: [:index] do
    resources :notifications, only:[:index, :show]
  end

  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/agreement_revision.rb
class AgreementRevision <ApplicationRecord
  include S3Configuration
  include Rails.application.routes.url_helpers
  belongs_to :agreement
  belongs_to :user
  before_create :set_revision_number
  attr_readonly :state

  default_scope -> { order('created_at DESC') }

  # draft: 0, validated_draft: 1, objected: 2, signed_draft:3 , validated:4 , rejected_sign:5, signed:6
  #
  # The lifecycle is handled by methods in the Agreement class. Those methods
  # create a new revision with the next state in the lifecycle — DO NOT change
  # the state of a specific revision in methods of this class. The possible
  # states are the following:
  #
  # 1. The initial agreement revision of a new agreement is born as "draft".
  #
  # 2. Next it is validated by consumer attorney, a new revision with the
  #   state "validated_draft" (See Agreement#validate_draft) is generated. Note
  #   that the attorney can't send the agreement back to the creator. If any
  #   change is required, it has to edit the agreement himself.
  #
  # 3. Then it is reviewed/signed by consumer undersecretary. Here a new revision
  #   with the state "signed_draft" (See Agreement#sign_draft) is created.
  #   Note that the undersecretary can't edit the agreement. If any change is
  #   required it has to object the agreement...
  #
  # 4. ...In which case a new agreement revision is created with the state
  #   "objected" (See Agreement#object_revision) and should be reviewed again by
  #   the attorney (Back to step 2)
  #
  # 5. Back to the happy path, a "signed_draft" from step 3 is then reviewed by
  #    the attorney of the provider organization. If everything looks OK to him,
  #    a new agreement revision will be created with the "validated" state
  #    (See Agreement#validate_revision). If something DOES NOT look OK to him,
  #    he can also object a revision...
  #
  # 6. ...In which case just like in step 4, a new agreement revision is created
  #    with the state  "objected" (See Agreement#object_revision) and the
  #    objections have to be reviewed by the attorney of the consumer (Back to
  #    step 2).
  #
  # 7. Again on the happy path: A "validated" agreement revision has to be
  #    signed by the provider organization's undersecretary, in which case the
  #    final revision of the agreement will be created with the "signed" state.
  #    (See Agreement#sign). But of course the undersecretary might NOT want to
  #    sign it...
  #
  # 8. ...In which case, a new agreement revision is created sith the
  #    "rejected_sign" state (See Agreement#reject_sign). Note that this is a
  #    different state than "objected" because the *provider*'s attorney has to
  #    look at the comments from his undersecretary and either edit/forward them
  #    to his counterpart (the consumer's attorney) or disagree with those
  #    comments and still recommend the agreement to be signed. In other words,
  #    we are back to step 5.
  #
  # ALWAYS add new states at the end.
  enum state: [:draft, :validated_draft, :objected, :signed_draft, :validated, :rejected_sign, :signed]

  def to_param
    revision_number.to_s
  end

  def set_revision_number
    self.revision_number = agreement.last_revision_number + 1
  end

  def upload_pdf(file_name, file_path)
    new_object = codegen_bucket.objects.build(file_name)
    new_object.content = open(file_path)
    new_object.content_type = 'application/pdf'
    new_object.save
    self.update(file: file_name)
  end

  def request_pdf_url
    begin
      object = codegen_bucket.objects.find(self.file)
      object.temporary_url
    rescue => e
      Rollbar.error('For Agreement id:' + self.agreement.id.to_s + ' revision: ' +
        self.revision_number.to_s + ' error whas: ' + e.to_s)
      return ''
    end
  end

  def send_notifications
    notify_responsables
    notify_next_step_responables
  end

  def create_notification_for_user(notify_user, email)
    notify_user.notifications.create(
      subject: self,
      message: I18n.t(:agreement_next_step_responsable_message,
                        id: agreement.id.to_s,
                        log: log,
                        responsable: user.name),
      email: email) unless notify_user.notifications.where(subject: self).exists?
  end

  def notify_responsables
    if self.revision_number > 1
      agreement.agreement_revisions.where("revision_number != ?", self.revision_number).each do |revision|
        create_notification_for_user(revision.user, revision.responsable_email)
      end
    end
  end

  def notify_next_step_responables
    next_step_users = agreement.next_step_responsables
    if !next_step_users.nil?
      next_step_users.each do |responsable|
        responsable[:email].each do |email|
          notify_user = User.where(name: responsable[:name]).first
          create_notification_for_user(notify_user, email) unless notify_user.nil?
        end
      end
    end
  end

  def responsable_email
    if revision_number == 1
      role = user.roles.where(name: "Create Agreement", organization: agreement.service_consumer_organization).first
      return role.email unless role.nil?
    else
      case state
      when 'draft', 'objected','validated_draft', 'signed_draft'
        role = user.roles.where(name: AgreementRevision.state_to_role(state), organization: agreement.service_consumer_organization).first
        return role.email unless role.nil?
      when 'validated', 'rejected_sign', 'signed'
        role = user.roles.where(name: AgreementRevision.state_to_role(state), organization: agreement.service_provider_organization).first
        return role.email unless role.nil?
      end
      return ''
    end
  end

  def url
    organization_agreement_agreement_revision_path(self.agreement.service_consumer_organization, self.agreement, self)
  end

  def self.state_to_role(state)
    case state
    when 'draft', 'validated_draft','objected',  'rejected_sign', 'validated'
      return "Validate Agreement"
    when  'signed', 'signed_draft'
      return "Sign Agreement"
    end
  end

end

app/controllers/agreement_revisions_controller.rb
class AgreementRevisionsController < ApplicationController
  include PdfGenerator
  before_action :set_agreement
  before_action :set_organization

  def show
    return unless user_signed_in?
    if (current_user.organizations.exists?(@agreement.service_provider_organization_id) ||
        current_user.organizations.exists?(@agreement.service_consumer_organization_id))
      @agreement_revision = @agreement.agreement_revisions.where(revision_number: params[:revision_number]).first
      if @agreement_revision.nil? || @agreement.last_revision_number != params[:revision_number].to_i
        redirect_to [@organization, @agreement, @agreement.last_revision]
      else
        @provider_organization = Organization.find(@agreement.service_provider_organization_id)
        @consumer_organization = Organization.find(@agreement.service_consumer_organization_id)
      end
    else
      redirect_to services_path, notice: t(:not_enough_permissions)
    end

  end

  def new
    return unless user_signed_in?
    if (current_user.organizations.exists?(@agreement.service_provider_organization_id) ||
        current_user.organizations.exists?(@agreement.service_consumer_organization_id))
      @agreement_revision = AgreementRevision.new
      @last_revision = @agreement.last_revision
      @provider_organization = Organization.find(@agreement.service_provider_organization_id)
      @consumer_organization = Organization.find(@agreement.service_consumer_organization_id)
    else
      redirect_to services_path, notice: t(:not_enough_permissions)
    end
  end

  def create
    @agreement_revision = @agreement.agreement_revisions.build(agreement_revision_params)
    @agreement_revision.user = current_user
    @agreement_revision.log = t(:modified_draft_log)
    if @agreement_revision.save!
      generate_pdf(@agreement, @agreement_revision)
      @agreement_revision.send_notifications
      redirect_to [@organization, @agreement, @agreement_revision], notice: t(:agreement_revision_edited)
    else
      render :new
    end
  end

private

  def agreement_revision_params
    params.require(:agreement_revision).permit(:purpose, :legal_base)
  end

  def set_agreement
    @agreement = Agreement.find(params[:agreement_id])
  end

  def set_organization
    @organization = Organization.find_by_name(params[:organization_name])
  end

end

app/helpers/agreement_revisions_helper.rb
module AgreementRevisionsHelper

  def agreement_consumer_sign_actions
    content_tag(:a, t(:reject), class: 'btn btn-danger',
      "data-target" => "#modalAgreementObjected", "data-toggle" => "modal", :type => "button") +
    content_tag(:a, t(:sign_request), class: 'btn btn-success',
      "data-target" => "#modalAgreementOneTimePassword", "data-toggle" => "modal", :type => "button")
  end

  def agreement_provider_validate_actions
    content_tag(:a, t(:reject), class: 'btn btn-danger',
      "data-target" => "#modalAgreementObjected", "data-toggle" => "modal", :type => "button")
  end

  def agreement_provider_sign_actions
    content_tag(:a, t(:reject), class: 'btn btn-danger',
      "data-target" => "#modalAgreementObjected", "data-toggle" => "modal", :type => "button") +
    content_tag(:a, t(:sign_request), class: 'btn btn-success',
      "data-target" => "#modalAgreementOneTimePassword", "data-toggle" => "modal", :type => "button")
  end

  def css_class_for_agreement_status(status)
    'btn-status ' + ({
      'draft' => 'static',
      'validated_draft' => 'primary',
      'objected' => 'danger',
      'signed_draft' => 'primary',
      'validated' => 'primary',
      'rejected_sign' => 'danger',
      'signed' => 'success'
    }[status] || '')
  end

  def buttons_assets
    {
      'draft' => [t(:edit), 'btn btn-default', t(:send_draft), 'btn btn-primary'],
      'objected' => [t(:edit), 'btn btn-default'],
      'signed_draft' => [t(:request_signature), 'btn btn-primary'],
      'rejected_sign' => [t(:send_draft), 'btn btn-primary']
    }[@agreement.state] || []
  end

  def modals_assets
    {
      'validated_draft' => agreement_consumer_sign_actions,
      'signed_draft' => agreement_provider_validate_actions,
      'validated' => agreement_provider_sign_actions,
      'rejected_sign' => agreement_provider_validate_actions
    }[@agreement.state] || ''
  end

end

app/views/agreement_revisions/_description_agreement.haml
%p
  =t(:applicant)+':'
  %strong= @consumer_organization.name
%p
  =t(:provider)+':'
  %strong= @provider_organization.name
%p
  =t(:application_date)+':'
  %strong= @agreement.created_at.strftime("%d/%m/%Y")
%br
%p
  %strong= t(:involved_services)
%ul
  - @agreement.services.each do |service|
    = content_tag(:li, service.name)

app/views/agreement_revisions/_history.haml
.box.history
  .header-box
    %span= t(:agreement_history)
  .body-box
    = render partial: "history_event", collection: @agreement.agreement_revisions

app/views/agreement_revisions/_history_event.haml
.event
  %p
    %strong= history_event.log
  %p
    #{t(:responsable)}: #{history_event.user.name}
    %br
    #{t(:contact)}: #{history_event.responsable_email}
    %br
    %small
      = history_event.created_at.strftime("%d/%m/%Y")

app/views/agreement_revisions/_modal_agreement_objected.html.haml
#modalAgreementObjected.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h1=t(:object_agreement)
      .modal-body
        = form_for @agreement, url: organization_agreement_change_state_path(@organization, @agreement, @agreement.next_step) do |f|
          %h3
            =t(:rejection_reason)
          = f.text_area :objection_message, value: @agreement.last_revision.objection_message
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"}
              =t(:cancel)
            %button.btn.btn-danger{:type => "submit"}
              =t(:reject)

app/views/agreement_revisions/_modal_agreement_one_time_password.html.haml
#modalAgreementOneTimePassword.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h1=t(:one_time_password)
      .modal-body
        = form_for @agreement, url: organization_agreement_change_state_path(@organization, @agreement, @agreement.next_step) do |f|
          .otp
            = text_field_tag :one_time_password
          .otp
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"}
              =t(:cancel)
            = f.button t(:sign_request), name: t(:sign_request), class: 'btn btn-success', id: "sign_request", 'data-loading-text': "<i class=\'fa fa-circle-o-notch fa-spin\'></i> " + t(:signing)

app/views/agreement_revisions/_next_step.haml
.box.next-step
  .header-box
    %span= t(:agreement_state)
    %span{class: css_class_for_agreement_status(@agreement_revision.state)}
      = t(@agreement_revision.state)
  - unless @agreement.signed? || @agreement.next_step_responsables.nil?
    .body-box
      .event
        %p
          %strong= t(:next_step)
          %br= t(@agreement.next_step + '_log')
        - @agreement.next_step_responsables.each do |responsable|
          %p
            = "Responsable: " + responsable[:name]
            %br
            Contacto:
            - responsable[:email].each do |email|
              = email

app/views/agreement_revisions/_user_allowed_actions.html.haml
= form_for @agreement, url: organization_agreement_change_state_path(@organization, @agreement, @agreement.next_step) do |f|
  - active_buttons = buttons_assets
  = modals_assets
  = active_buttons.in_groups_of(2) do |button|
    = f.button button[0], name: button[0], class: button[1]

app/views/agreement_revisions/new.html.haml
- if !user_signed_in?
  .alert.info
    .container
      %p
        #{t(:to_create_agreements_please)}
        = link_to t(:identify_with_clave_unica), user_clave_unica_omniauth_authorize_path
- else
  .show-agreement.main-container
    .container-fluid.main-title
      .container
        .col-md-12
          %h1= t(:agreement_between, consumer: @agreement.service_consumer_organization.name, provider: @agreement.service_provider_organization.name)
          %a{:href => 'index', :title => 'Cancelar'}
            %i.material-icons
              close

    .container-fluid.show-agreement-content
      .container
        .row
          .col-md-9
            .description
              = render partial: "description_agreement"
            %form
            = form_for([@organization, @agreement, @agreement_revision], :html => {class: 'form-group'}) do |f|
              .visor.form_content
                %p
                  %strong= t(:purpose)+':'
                  = f.text_area :purpose, class: 'form-control', value: @last_revision.purpose
              .visor.form_content
                %p
                  %strong= t(:legal_base)+':'
                  = f.text_area :legal_base, class: 'form-control', value: @last_revision.legal_base
              .actions
                = f.submit class: 'btn btn-success', value: t(:save)
                = link_to t(:cancel), :back, class: 'btn btn-static'

          .col-md-3
            = render partial: "next_step"
            = render partial: "history"

app/views/agreement_revisions/show.html.haml
- if !user_signed_in?
  .alert.info
    .container
      %p
        #{t(:to_review_agreements_please)}
        = link_to t(:identify_with_clave_unica), user_clave_unica_omniauth_authorize_path
- else
  .show-agreement.main-container
    .container-fluid.main-title
      .container
        .col-md-12
          %h1= t(:agreement_between, consumer: @agreement.service_consumer_organization.name, provider: @agreement.service_provider_organization.name)
          %a{:href => 'index', :title => 'Cancelar'}
          = link_to organization_agreements_path(@consumer_organization) do
            %i.material-icons
              close

    - if user_signed_in? && (@agreement_revision.objected? || @agreement_revision.rejected_sign?)
      .container-fluid.panel-error.alert.fade.in{:"data-alert" => "alert"}
        .container
          .row
            .col-md-12
              %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
              %h1= t(:objected_log)
              %p= @agreement_revision.objection_message

    .container-fluid.show-agreement-content
      .container
        .row
          .col-md-9
            .description
              = render partial: "description_agreement"
              %br
              %p
                %strong= t(:purpose)+':'
                = @agreement_revision.purpose
            .visor
              .preview
                %embed{:src => @agreement_revision.request_pdf_url, :width => '100%', :height => '493'}

            .actions
              = render partial: 'user_allowed_actions' if @agreement.user_can_update_agreement_status?(current_user)

              = link_to @agreement_revision.request_pdf_url, download: '', :title => t(:download_pdf), :class => 'to-link' do
                %i.material-icons
                  get_app
                %span= t(:download_pdf)
              - if current_user.can_see_credentials_for_agreement?(@agreement)
                = link_to '#modalTokens', class: "to-link", data: {target: '#modalTokens', toggle: 'modal'} do
                  %i.material-icons lock
                  = t(:tokens)

          .col-md-3
            = render partial: "next_step"
            = render partial: "history"
  = render partial: "modal_agreement_objected" if %w(validated validated_draft signed_draft rejected_sign).include?(@agreement_revision.state)
  = render partial: "modal_agreement_one_time_password" if %w(validated_draft validated rejected_sign).include?(@agreement_revision.state)

#modalTokens.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h1
          =t(:tokens)
      .modal-body
        - if current_user.can_see_credentials_for_agreement?(@agreement)
          .row
            .col-md-3
              %h4 Client ID:
            .col-md-9
              %pre= @agreement.id
          .row
            .col-md-3
              %h4 Client Secret:
            .col-md-9
              %pre= @agreement.client_secret
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"}
          =t(:close)