config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'static_pages/visual_components'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'home#root'

  get 'trazabilidad', to: 'traceability#endpoints_info'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :schemas, only: [:index, :new, :create], param: :name do
    collection { get 'search' }
    resources :schema_versions,
      only: [:index, :new, :create, :show], param: :version_number,
      path: 'versions'
  end

  resources :services, only: [:index], controller: 'home' do
    collection do
      get 'search'
      get 'pending_approval'
    end
  end

  namespace :agreements do
    get 'global'
    get 'new_injection'
    post 'inject'
  end

  namespace :monitoring do
    resources :organizations, only: [:index], param: :name do
      resources :services, only: [:index, :show], param: :name do
        member do
          post 'enable'
          post 'disable'
        end
      end
    end
  end

  resources :monitor_params
  resources :data_categories
  resources :data_directories, only: :index

  resources :organizations, only: [:index, :show], param: :name do
    resources :services, only: [:index, :new, :create, :show], param: :name do
      post 'oauth/token', to: 'services#client_token'
      resources :service_versions,
        only: [:index, :new, :create, :show], param: :version_number,
        path: 'versions' do
          member do
            patch 'reject'
            patch 'state'
            get 'source_code'
            get 'operations/:verb*path', to: 'service_versions#show', as: 'operation', constraints: {path: /\/.*/}
            get 'operations/:verb', to: 'service_versions#show', as: 'operation_on_root_path'
            post 'operations/:verb*path', to: 'service_versions#try', as: 'try_operation', constraints: {path: /\/.*/}
            post 'operations/:verb', to: 'service_versions#try', as: 'try_operation_on_root_path'
          end
      end
    end

    resources :agreements, only: [:index, :new, :create, :show] do
      patch 'state/:next_step' => 'agreements#flow_actions_router', as: 'change_state'
      resources :agreement_revisions, only: [:show, :new, :create], param: :revision_number,
        path: 'revisions'
    end
  end

  resources :users, only: [:index] do
    resources :notifications, only:[:index, :show]
  end

  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def root
    redirect_to services_path
  end

  def index
    @featured_services = Service.featured
    @popular_services = Service.popular
  end

  def search
    @text_search = params[:text_search]
    organization = Organization.where(name: @text_search).first
    if organization.blank?
      @services = Service.search(params[:text_search])
    else
      @services = organization.services
    end
  end

  def pending_approval
    return unless user_signed_in?
    if current_user.is_service_admin?
      @pending_services_version = ServiceVersion.proposed
    else
      redirect_to root_path, notice: t(:not_enough_permissions)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_boxes.html.haml
- services.each do |s|
  .box-service
    %h2.title{class: ('opendata' if s.public)}
      = link_to operation_organization_service_service_version_path(organization_name: s.organization.name, 
                                                                    version_number: s.last_version.version_number, 
                                                                    service_name: s.name, 
                                                                    verb: s.last_version.get_info_from_first_service("verb"), 
                                                                    path: s.last_version.get_info_from_first_service("path"), 
                                                                    anchor: 'operation') do
        = truncate(s.name, :length => 50)
    .body
      - if s.description.blank?
        = t(:no_description)
      - else
        = truncate(s.description, :length => 70)
      = link_to s.organization.name, search_services_path(text_search: s.organization.name), class: 'organization'

app/views/home/_pending.html.haml
%tr{data: {name: pending.name, link: organization_service_service_version_path(pending.service.organization, pending.service, pending)}}
  %td= pending.created_at.strftime("%d/%m/%Y")
  %td= pending.name
  %td= pending.organization.name
  %td
    %span{ class: 'btn btn-tiny static' }
      = 'R' + pending.version_number.to_s
  %td= pending.user.name
  %td
    %span{class: css_class_for_status(pending.status)}
      = t(pending.status)

app/views/home/index.html.haml
.instance-panel
  .container
    .col-md-12{:class => "text-center"}
      %h1= t(:service_directory)
      .form-group.col-md-8.container-form
        = form_tag(search_services_path, :method => "get") do
          .inner-addon.left-addon
            %i.glyphicon.glyphicon-search
            %input#search-service.form-control{:placeholder => t(:enter_service_name), :type => "text", :name => "text_search"}/
.container-fliud.list-services-home
  .container
    .row
      .col-md-12
        %ul.nav.nav-tabs{:role => "tablist"}
          %li.active{:role => "presentation"}
            %a{"aria-controls" => "#featured", "data-toggle" => "tab", :href => "#featured", :role => "tab"} Servicios Destacados
          %li{:role => "presentation"}
            %a{"aria-controls" => "#popular", "data-toggle" => "tab", :href => "#popular", :role => "tab"} Servicios Más Usados
  .container-fluid.tab-content
    #featured.tab-pane.active{role: 'tabpanel'}
      .container
        .row
          .col-md-12.schema-wrapper.text-left
            = render partial: "boxes", locals: {services: @featured_services}
    #popular.tab-pane{role: 'tabpanel'}
      .container
        .row
          .col-md-12.schema-wrapper.text-left
            = render partial: "boxes", locals: {services: @popular_services}

app/views/home/pending_approval.html.haml
- unless user_signed_in? && current_user.is_service_admin?
  .alert.info
    .container
      %p
        #{t(:to_review_services_please)}
        = link_to t(:identify_with_clave_unica), user_clave_unica_omniauth_authorize_path
- else

  .content-pages.content-tabs
    .container
      .tab-content
        #services.tab-pane.active{:role => "tabpanel"}
          - if @pending_services_version.empty?
            .row
              .col-md-12.head-title-table
                %h2= t(:no_services_pending_approval)
          - else
            .row
              .col-md-12.head-title-table
                %h2= t(:new_requests_pending_approval, count: @pending_services_version.count)
                .search-table
                  %input.search-filter{:type => 'text', :placeholder => t(:name_search), data: {target: '#services-table'}}
                  %button.search
                    %i.material-icons
                      search
            .row
              .col-md-12
                %table#services-table
                  %colgroup
                    %col{:width => "10%"}
                    %col
                    %col{:width => "22%"}
                    %col{:width => "8%"}
                    %col{:width => "12%"}
                    %col{:width => "8%"}
                  %thead
                    %tr
                      %th Fecha
                      %th= t(:service_name)
                      %th= t(:requesting_organization)
                      %th= t(:version)
                      %th= t(:requester)
                      %th= t(:state)
                  %tbody
                    = render partial: "pending", collection: @pending_services_version

app/views/home/search.html.haml
.instance-panel
  .container
    .col-md-12{:class => "text-center"}
      %h1= t(:service_directory)
      .form-group.col-md-6.container-form
        = form_tag(search_services_path, method: "get") do
          .inner-addon.left-addon
            %i.glyphicon.glyphicon-search
            %input#search-service.form-control{:value => @text_search, :type => "text", :name => "text_search"}/
.container
  .row.no-gutter
    .col-md-12.schema-wrapper.text-left
      = content_tag(:p, t(:no_results_found), class:"text-center") if @services.empty?
      = render partial: "boxes", locals: {services: @services}