config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'static_pages/visual_components'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'home#root'

  get 'trazabilidad', to: 'traceability#endpoints_info'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :schemas, only: [:index, :new, :create], param: :name do
    collection { get 'search' }
    resources :schema_versions,
      only: [:index, :new, :create, :show], param: :version_number,
      path: 'versions'
  end

  resources :services, only: [:index], controller: 'home' do
    collection do
      get 'search'
      get 'pending_approval'
    end
  end

  namespace :agreements do
    get 'global'
    get 'new_injection'
    post 'inject'
  end

  namespace :monitoring do
    resources :organizations, only: [:index], param: :name do
      resources :services, only: [:index, :show], param: :name do
        member do
          post 'enable'
          post 'disable'
        end
      end
    end
  end

  resources :monitor_params
  resources :data_categories
  resources :data_directories, only: :index

  resources :organizations, only: [:index, :show], param: :name do
    resources :services, only: [:index, :new, :create, :show], param: :name do
      post 'oauth/token', to: 'services#client_token'
      resources :service_versions,
        only: [:index, :new, :create, :show], param: :version_number,
        path: 'versions' do
          member do
            patch 'reject'
            patch 'state'
            get 'source_code'
            get 'operations/:verb*path', to: 'service_versions#show', as: 'operation', constraints: {path: /\/.*/}
            get 'operations/:verb', to: 'service_versions#show', as: 'operation_on_root_path'
            post 'operations/:verb*path', to: 'service_versions#try', as: 'try_operation', constraints: {path: /\/.*/}
            post 'operations/:verb', to: 'service_versions#try', as: 'try_operation_on_root_path'
          end
      end
    end

    resources :agreements, only: [:index, :new, :create, :show] do
      patch 'state/:next_step' => 'agreements#flow_actions_router', as: 'change_state'
      resources :agreement_revisions, only: [:show, :new, :create], param: :revision_number,
        path: 'revisions'
    end
  end

  resources :users, only: [:index] do
    resources :notifications, only:[:index, :show]
  end

  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/schema.rb
class Schema < ApplicationRecord
  include Searchable
  has_and_belongs_to_many :schema_categories
  has_many :schema_versions
  has_many :schema_data_categories
  has_many :data_categories, through: :schema_data_categories

  validates :name, uniqueness: true, presence: true
  attr_accessor :spec
  validates :spec, swagger_schema_object: true, presence: true
  before_save :update_humanized_name
  delegate :description, to: :last_version
  validate :spec_file_must_be_parseable
  attr_accessor :spec_file_parse_exception


  def spec_file_must_be_parseable
    if self.spec_file_parse_exception
      errors.add(:spec_file, "Archivo no está en formato JSON o YAML")
    end
  end

  def spec_file
    @spec_file
  end

  def spec_file=(spec_file)
    self.spec_file_parse_exception = nil
    @spec_file = spec_file
    self.spec = YAML.safe_load(spec_file.read)
  rescue Psych::SyntaxError => e
    self.spec_file_parse_exception = e
  end

  def to_param
    name
  end

  def create_first_version(user)
    schema_versions.create(spec: self.spec, user: user)
  end

  def last_version_number
    schema_versions.maximum(:version_number) || 0
  end

  def last_version
    schema_versions.order('version_number desc').first
  end

  def update_humanized_name
    self.humanized_name = self.name.underscore.humanize
  end

  # Required by Searchable to (re)build its index
  def text_search_vectors
    vectors = [
      Searchable::SearchVector.new(name, 'A'),
      Searchable::SearchVector.new(humanized_name, 'A')
    ]
    version = last_version
    unless version.nil?
      vectors.concat(spec_search_vector_extractor.search_vectors(
        version.spec
      ))
    end
    vectors
  end

  def spec_search_vector_extractor
    keys_to_search_for = %w(title description)
    weight_by_path_pattern = {
      /^title$/ => 'A',
      /^description$/ => 'B',
      /^properties > [^>]* > description$/ => 'C',
      /^.*$/ => 'D' # Anything else nested inside properties will get lower
                    # weight
    }
    HashSearchVectorExtractor.new(keys_to_search_for, weight_by_path_pattern)
  end
end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController

  def index
    @categories = SchemaCategory.all
    @schemas = Schema.all
  end

  def new
    return unless user_signed_in?
    if current_user.can_create_schemas
      @schema = Schema.new
      @categories = SchemaCategory.all
    else
      redirect_to schemas_path, notice: t(:not_enough_permissions)
    end
  end

  def create
    @schema = Schema.new(schema_params)
    if @schema.save
      @schema.create_first_version(current_user)
      @schema.data_category_ids = params[:schema][:data_category_ids].reject(&:blank?)
      redirect_to [@schema, @schema.schema_versions.first], notice: t(:new_schema_created)
    else
      flash.now[:error] = t(:cant_create_schema)
      render action: "new"
    end
  end

  def search
    @text_search = params[:text_search]
    @schemas = Schema.search(params[:text_search])
  end

  private

  def schema_params
    params.require(:schema).permit(:schema_category_ids, :name, :spec_file, :data_category_ids, 'data_category_ids')
  end

  def set_schema
    @schema = Schema.where(name: params[:name]).take
  end
end

app/helpers/schemas_helper.rb
module SchemasHelper
end

app/views/schemas/index.html.haml
.instance-panel
  .container
    .col-md-12{:class => "text-center"}
      %h1= t(:schema_directory)
      .form-group.col-md-8.container-form
        = form_tag(search_schemas_path, method: "get") do
          .inner-addon.left-addon
            %i.glyphicon.glyphicon-search
            %input#search-schema.form-control{:placeholder => t(:enter_schema_name), :type => "text", :name => "text_search"}/
.container
  .row
    .col-md-2.sidebar
      %h3.col-title=SchemaCategory.model_name.human(count: 2)
      %ul#categories-list.list-categories
        - @categories.with_schemas.each do |category|
          %li
            %a{data: {category: category.id}}
              = category.name

    .col-md-10.schema-wrapper
      .schema-box-container
        - @schemas.each do |schema|
          .box-schema.active{data: {categories:schema.schema_category_ids.join(' ')}}
            .title
              = link_to [schema, schema.last_version] do
                = truncate(schema.name, :length => 50)
            .body
              %span
                -#{t(:description)}:
              = truncate(schema.description, :length => 183)

app/views/schemas/new.html.haml
- if !user_signed_in?
  .alert.info
    .container
      %p
        #{t(:to_upload_a_schema_please)}
        = link_to t(:identify_with_clave_unica), user_clave_unica_omniauth_authorize_path
- else
  = form_for @schema do |f|
    - if @schema.errors.any?
      .container-fluid.no-gutter{:class => "alert warning alert-dismissable fade in", :"data-alert" => "alert"}
        .row
          .container
            %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
            %p= t(:cant_save_schema_error, count: @schema.errors.count)
            %ul
              - @schema.errors.full_messages.each do |message|
                %li= message
    .new-agreement.main-container
      .container-fluid.main-title
        .container
          .row
            .col-md-12
              %h1
                Creación de Nuevo Esquema
              %a{:href => "javascript:history.back();"}
                %i.material-icons
                  close

      .container-fluid
        .container
          .row.new-service-container
            .col-md-4
              %h4= t(:create_schema)
              .input-group.box-input-file
                .field
                  %input#input-file.form-control{:readonly => 'readonly', :type => 'text'}
                %label#label-file.input-group-btn
                  %span#select-file.btn= t(:select_file)
                  = f.file_field :spec_file, :style => 'display: none;', readonly: 'readonly'
              %span#remove-file
                %i.material-icons{":aria-hidden" => true} close
                %span=t(:remove_file)

            .col-md-4
              %h4= t(:enter_new_schema_name)
              = f.text_field :name, { :class => "form-control input-lg", :placeholder => t(:schema_name_example)}
            .col-md-4
              %h4= t(:enter_new_schema_category)
              = f.collection_select 'schema_category_ids', SchemaCategory.all, :id, :name, {:include_blank => false}, {:class => 'form-control input-lg'}
              
            .col-md-4.col-md-pull-4{style: "margin-top: 2rem"}
              %h4= t(:enter_new_schema_data_category)
              = f.select :data_category_ids, [], {}, {multiple: "multiple", class: "form-control", id: "tagPicker"} do 
                - DataCategory.all.each do |cat|
                  = content_tag(:option, cat.name, value: cat.id, selected: @schema.data_categories.pluck(:id).include?(cat.id))
  
          .row
            .col-md-12
              .text-right
                = f.submit t(:create_schema), class: 'btn btn-primary btn-lg', id: "create-schema"

app/views/schemas/search.html.haml
.instance-panel
  .container
    .col-md-12{:class => "text-center"}
      %h1= t(:schema_directory)
      .form-group.col-md-8.container-form
        = form_tag(search_schemas_path, method: "get") do
          .inner-addon.left-addon
            %i.glyphicon.glyphicon-search
            %input#search-schema.form-control{:value => @text_search, :type => "text", :name => "text_search"}/
.container
  .row
    .col-md-12.schema-wrapper.text-left
      = content_tag(:h4, t(:no_results_found),
        class:"text-center") if @schemas.empty?
      - @schemas.each do |schema|
        .box-service
          .title
            = link_to [schema, schema.last_version] do
              = truncate(schema.name, :length => 50)
          .body
            %span
              #{t(:description)}:
            = truncate(schema.description, :length => 183)